test_dat = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^..g^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


def load_input(test: bool = False) -> list[list[str]]:
    if test:
        dat = test_dat.strip()
    else:
        with open("./2025/input/day_7.txt") as f:
            dat = f.read().strip()

    return [list(x) for x in dat.splitlines()]
